PROJECT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('database/', admin.site.urls),
    path('auth/', include('auth_app.urls')),
    path('admin/', include('admin_app.urls')),
    path('', include('user_app.urls')),  
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_app/urls.py
from django.urls import path
from admin_app.views import *

urlpatterns = [
    path('', dashboard, name='dashboard'),
    
    path('projects/', project_list, name='project_list'),
    path('projects/add/', project_add, name='project_add'),
    path('projects/<int:project_id>/view/', project_view, name='project_view'),
    path('projects/<int:project_id>/edit/', project_edit, name='project_edit'),
    path('projects/<int:project_id>/delete/', project_delete, name='project_delete'),
    
    path('products/', product_list, name='product_list'),
    path('products/add/', product_add, name='product_add'),
    path('products/<int:product_id>/view/', product_view, name='product_view'),
    path('products/<int:product_id>/edit/', product_edit, name='product_edit'),
    path('products/<int:product_id>/delete/', product_delete, name='product_delete'),
    
    path('message/list/', message_list, name='message_list'),
    path('message/<int:message_id>/view', message_view, name='message_view'),
]

admin_app/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    image = models.ImageField(upload_to='admin_app/products')
    head = models.CharField(max_length=500, null=True, blank=True)
    description = models.CharField(max_length=1000, null=True, blank=True)
    
class Project(models.Model):
    image = models.ImageField(upload_to='admin_app/projects')
    head = models.CharField(max_length=500, null=True, blank=True)
    description = models.CharField(max_length=1000, null=True, blank=True)
    status = models.BooleanField(default=False)
    

class Message(models.Model):
    name = models.CharField(max_length=500, null=True, blank=True)
    phone = models.CharField(max_length=500, null=True, blank=True)
    email = models.CharField(max_length=500, null=True, blank=True)
    message = models.CharField(max_length=1000, null=True, blank=True)

admin_app/views.py
from django.shortcuts import render, redirect
from admin_app.models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url='/auth/admin/login/')
def dashboard(request):
    current_page = 'dashboard'
    total_messages = Message.objects.count()
    total_products = Product.objects.count()
    total_projects = Project.objects.count()
    context = {
        'current_page': current_page,
        'total_products': total_products,
        'total_projects': total_projects,
        'total_messages': total_messages,
    }
    return render(request, 'admin_app/pages/dashboard.html', context)


#-------------------------------------------- Products ------------------------------------------------------#

@login_required(login_url='/auth/admin/login/')    
def product_list(request):
    current_page = 'product_list'
    products = Product.objects.all()
    context = {
        'current_page': current_page,
        'products': products
        }
    return render(request, 'admin_app/pages/product_list.html', context)

@login_required(login_url='/auth/admin/login/')
def product_view(request, product_id):
    current_page = 'product_view'
    try:
        product = Product.objects.get(id=product_id)
    except Product.DoesNotExist:
        messages.error(request, 'product not found')
        return redirect('product_list')
    context = {
        'current_page': current_page,
        'product':product
    }
    return render(request, 'admin_app/pages/product_view.html', context)

@login_required(login_url='/auth/admin/login/')
def product_add(request):
    current_page = 'product_add'
    if request.method == 'POST':
        image = request.FILES.get('image') 
        head = request.POST.get('head')
        description = request.POST.get('description')
        
        try:
            product = Product(
                image=image,
                head=head,
                description=description,
            )
            product.save()
            messages.success(request, 'product added successfully')
            return redirect('product_list')
        except Exception as e:
            messages.error(request, f'Error adding product: {e}')
            return redirect('product_add')
        
    context = {
        'current_page': current_page,
    } 
    return render(request, 'admin_app/pages/product_add.html', context)

@login_required(login_url='/auth/admin/login/')
def product_edit(request, product_id):
    current_page = 'product_edit'
    try:
        product = Product.objects.get(id=product_id)
    except Product.DoesNotExist:
        messages.error(request, 'product not found')
        return redirect('product_list')

    if request.method == 'POST':
        try:
            image = request.FILES.get('image')
            product.head = request.POST.get('head')
            product.description = request.POST.get('description')
            

            # Update the image field
            if image:
                product.image = image

            product.save()
            messages.success(request, 'product edited successfully')
            return redirect('product_list')
        except Exception as e:
            messages.error(request, f'Error editing product: {e}')
            return redirect('product_edit', product_id=product.id) 

    context = {
        'current_page': current_page,
        'product': product
        }
    return render(request, 'admin_app/pages/product_edit.html', context)

@login_required(login_url='/auth/admin/login/')
def product_delete(request, product_id):
    try:
        product = Product.objects.get(id=product_id)
    except Product.DoesNotExist:
        messages.error(request, 'product not found')
        return redirect('product_list')
    
    try: 
        product.delete()
        messages.success(request, 'product deleted successfully')
        return redirect('product_list')
    except Exception as e:
        messages.error(request, f'Error deleting product: {e}')
        return redirect('product_list')


@login_required(login_url='/auth/admin/login/')#-------------------------------------------- Projects ------------------------------------------------------#
def project_list(request):
    current_page = 'project_list'
    projects = Project.objects.all()
    context = {
        'current_page': current_page,
        'projects': projects
        }
    return render(request, 'admin_app/pages/project_list.html', context)

@login_required(login_url='/auth/admin/login/')
def project_view(request, project_id):
    current_page = 'project_view'
    try:
        project = Project.objects.get(id=project_id)
    except Project.DoesNotExist:
        messages.error(request, 'Project not found')
        return redirect('project_list')
    context = {
        'current_page': current_page,
        'project':project
    }
    return render(request, 'admin_app/pages/project_view.html', context)

@login_required(login_url='/auth/admin/login/')
def project_add(request):
    current_page = 'project_add'
    if request.method == 'POST':
        image = request.FILES.get('image') 
        head = request.POST.get('head')
        description = request.POST.get('description')
        # status = request.POST.get('status') == 'on'
        try:
            project = Project(
                image=image,
                head=head,
                description=description,
                status=True,
            )
            project.save()
            messages.success(request, 'Project added successfully')
            return redirect('project_list')
        except Exception as e:
            messages.error(request, f'Error adding project: {e}')
            return redirect('project_add')
        
    context = {
        'current_page': current_page,
    } 
    return render(request, 'admin_app/pages/project_add.html', context)

@login_required(login_url='/auth/admin/login/')
def project_edit(request, project_id):
    current_page = 'project_edit'
    try:
        project = Project.objects.get(id=project_id)
    except Project.DoesNotExist:
        messages.error(request, 'Project not found')
        return redirect('project_list')

    if request.method == 'POST':
        try:
            image = request.FILES.get('image')
            project.head = request.POST.get('head')
            project.description = request.POST.get('description')
            # project.status = request.POST.get('status') == 'on'

            # Update the image field
            if image:
                project.image = image

            project.save()
            messages.success(request, 'Project edited successfully')
            return redirect('project_list')
        except Exception as e:
            messages.error(request, f'Error editing project: {e}')
            return redirect('project_edit', project_id=project.id) 

    context = {
        'current_page': current_page,
        'project': project
        }
    return render(request, 'admin_app/pages/project_edit.html', context)

@login_required(login_url='/auth/admin/login/')
def project_delete(request, project_id):
    try:
        project = Project.objects.get(id=project_id)
    except Project.DoesNotExist:
        messages.error(request, 'Project not found')
        return redirect('project_list')
    
    try: 
        project.delete()
        messages.success(request, 'Project deleted successfully')
        return redirect('project_list')
    except Exception as e:
        messages.error(request, f'Error deleting project: {e}')
        return redirect('project_list')
    


    

    
#-------------------------------------------- Message ------------------------------------------------------#   

@login_required(login_url='/auth/admin/login/')    
def message_list(request):
    current_page = 'message_list'
    messages = Message.objects.all().order_by('-id')
    context = {
        'current_page': current_page,
        'messages': messages
        }
    return render(request, 'admin_app/pages/message_list.html', context)

@login_required(login_url='/auth/admin/login/')
def message_view(request, message_id):
    current_page = 'message_view'
    try:
        message = Message.objects.get(id=message_id)
    except Message.DoesNotExist:
        messages.error(request, 'Message not found')
        return redirect('message_list')
    context = {
        'current_page': current_page,
        'message': message
        }
    return render(request, 'admin_app/pages/message_view.html', context)

templates/admin_app/pages/dashboard.html
{% extends "admin_app/components/base.html" %}
{% load static %}
{% block content %}

{% include 'admin_app/components/header.html' %}
<div class="container-fluid py-4">
  {% include 'admin_app/components/alert.html' %}
  <div class="row">
    <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
      <div class="card">
        <div class="card-body p-3">
          <div class="row">
            <div class="col-8">
              <div class="numbers">
                <p class="text-sm mb-0 text-uppercase font-weight-bold">Total Product</p>
                <h5 class="font-weight-bolder mb-0 ">
                  {{ total_products }}
                </h5>
                <!-- <p class="mb-0">
                  <span class="text-success text-sm font-weight-bolder">+55%</span>
                  since yesterday
                </p> -->
              </div>
            </div>
            <div class="col-4 text-end">
              <div class="icon icon-shape bg-gradient-primary shadow-primary text-center rounded-circle">
                <i class="ni ni-calendar-grid-58 text-lg opacity-10" aria-hidden="true"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
      <div class="card">
        <div class="card-body p-3">
          <div class="row">
            <div class="col-8">
              <div class="numbers">
                <p class="text-sm mb-0 text-uppercase font-weight-bold">Toatal Project</p>
                <h5 class="font-weight-bolder">
                  {{ total_projects }}
                </h5>
                <!-- <p class="mb-0">
                  <span class="text-success text-sm font-weight-bolder">+3%</span>
                  since last week
                </p> -->
              </div>
            </div>
            <div class="col-4 text-end">
              <div class="icon icon-shape bg-gradient-danger shadow-danger text-center rounded-circle">
                <i class="ni ni-calendar-grid-58 text-lg opacity-10" aria-hidden="true"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
      <div class="card">
        <div class="card-body p-3">
          <div class="row">
            <div class="col-8">
              <div class="numbers">
                <p class="text-sm mb-0 text-uppercase font-weight-bold">Total Messages</p>
                <h5 class="font-weight-bolder">
                  {{ total_messages }}
                </h5>
                
              </div>
            </div>
            <div class="col-4 text-end">
              <div class="icon icon-shape bg-gradient-success shadow-success text-center rounded-circle">
                <i class="ni ni-calendar-grid-58 text-lg opacity-10" aria-hidden="true"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> -->
    <div class="col-xl-3 col-sm-6">
      <div class="card">
        <div class="card-body p-3">
          <div class="row">
            <div class="col-8">
              <div class="numbers">
                <p class="text-sm mb-0 text-uppercase font-weight-bold">Total Messages</p>
                <h5 class="font-weight-bolder">
                  {{ total_messages }}
                </h5>
                <!-- <p class="mb-0">
                  <span class="text-success text-sm font-weight-bolder">+5%</span> than last month
                </p> -->
              </div>
            </div>
            <div class="col-4 text-end">
              <div class="icon icon-shape bg-gradient-warning shadow-warning text-center rounded-circle">
                <i class="ni ni-credit-card text-lg opacity-10" aria-hidden="true"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="card mt-5">
    <div class="card-body">
      <h3 class="pb-3">Pages</h3>
      <ul style="list-style: none;">
        <li class="pb-2">
          <span style="color: green;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
              <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0M4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5z"/>
            </svg>
          </span>
          <span>
            <a href="{% url 'dashboard' %}">Dashboard</a>
          </span>
        </li>

        <li class="pb-2">
            <span style="color: green;">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0M4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5z"/>
              </svg>
            </span>
            <span>
              <a href="{% url 'product_add' %}">Product Add</a>
            </span>
          </li>
  
          <li class="pb-2">
            <span style="color: green;">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0M4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5z"/>
              </svg>
            </span>
            <span>
              <a href="{% url 'product_list' %}">Product List</a>
            </span>
          </li>

        <li class="pb-2">
          <span style="color: green;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
              <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0M4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5z"/>
            </svg>
          </span>
          <span>
            <a href="{% url 'project_add' %}">Project Add</a>
          </span>
        </li>

        <li class="pb-2">
          <span style="color: green;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
              <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0M4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5z"/>
            </svg>
          </span>
          <span>
            <a href="{% url 'project_list' %}">Project List</a>
          </span>
        </li>
        <li class="pb-2">
          <span style="color: green;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
              <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0M4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5z"/>
            </svg>
          </span>
          <span>
            <a href="{% url 'message_list' %}">Messages</a>
          </span>
        </li>
      </ul>
    </div>
  </div>
    
  
    
  
</main>
{% endblock content %}

templates/admin_app/pages/message_list.html
{% extends "admin_app/components/base.html" %}
{% load static %}
{% block content %}

{% include 'admin_app/components/header.html' %}

<div class="container-fluid py-4">
  {% include 'admin_app/components/alert.html' %}
    <div class="row">
      <div class="col-12">
        <div class="card mb-4">
          <div class="card-header pb-0">
            <div class="row">
                <div class="col-6 d-flex align-items-center">
                  <h6 class="mb-0">message List</h6>
                </div>
                <div class="col-6 text-end">
                    
                  
                </div>
            </div>
          </div>
          <div class="card-body px-0 pt-0 pb-2">
            <div class="table-responsive p-0">
              <table class="table align-items-center mb-0">
                <thead>
                    <tr class="text-center">
                      <th scope="col">#</th>
                      <th scope="col">Name</th>
                      <th scope="col">Phone</th>
                      <th scope="col">Email</th>
                      <th scope="col">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for message in messages %}
                    <tr class="text-center">
                      <th scope="row">{{ forloop.counter }}</th>
                      <td>
                        {{ message.name }}
                      </td>
                    
                      <td class="align-middle text-center text-sm">
                        {{ message.phone }}
                      </td>

                      <td class="align-middle text-center text-sm">
                        {{ message.email }}
                      </td>
                      <td>
                        <span>
                            <a href="{% url 'message_view' message.id %}">
                                <i class="bi bi-eye-fill text-primary"></i>
                            </a>
                        </span>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    
</div>
</main>
{% endblock content %}

templates/admin_app/pages/product_add.html
{% extends "admin_app/components/base.html" %}
{% load static %}
{% block content %}

{% include 'admin_app/components/header.html' %}
<div class="container-fluid py-4">
    {% include 'admin_app/components/alert.html' %}
    <div class="row">
        <div class="col-md-12">
        <div class="card">
            <div class="card-header pb-0">
            <div class="d-flex align-items-center">
                <p class="mb-0">Add Product</p>
                
            </div>
            </div>
            <div class="card-body">
                
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_image" class="form-control-label">Image:690 x 500px</label>
                            
                            <input type="file" name="image" class="form-control" required>
                        </div>
                        </div>
                        <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_head" class="form-control-label">Head:</label>
                            <input type="text" name="head" maxlength="500" class="form-control" >
                        </div>
                        </div>
                        <div class="col-md-12">
                        <div class="form-group">
                            <label for="id_description" class="form-control-label">Description:</label>
                            <textarea name="description" maxlength="1000" class="form-control" ></textarea>
                        </div>
                        </div>
                        
                        <div class="col-md-12 d-flex justify-content-end">
                            <button class="btn btn-primary" type="submit">Add Product</button>
                        </div>
                    </div>
                </form>
            
            </div>
        </div>
    </div>
        
</div>


</main>
{% endblock content %}

templates/admin_app/pages/product_edit.html
{% extends "admin_app/components/base.html" %}
{% load static %}
{% block content %}

{% include 'admin_app/components/header.html' %}
<div class="container-fluid py-4">
    {% include 'admin_app/components/alert.html' %}
    <div class="row">
        <div class="col-md-12">
        <div class="card">
            <div class="card-header pb-0">
            <div class="d-flex align-items-center">
                <p class="mb-0">Edit product</p>
                
            </div>
            </div>
            <div class="card-body">
                
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_image" class="form-control-label">Image:690 x 500px</label>
                            <input type="file" name="image"  class="form-control" >
                        </div>
                        </div>
                        <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_head" class="form-control-label">Head:</label>
                            <input type="text" name="head" value="{{ product.head }}" maxlength="500" class="form-control" >
    
                        </div>
                        </div>
                        <div class="col-md-12">
                        <div class="form-group">
                            <label for="id_description" class="form-control-label">Description:</label>
                            <textarea name="description" maxlength="1000" class="form-control" >{{ product.description }}</textarea>
                        </div>
                        </div>
                        
                        <div class="col-md-12 d-flex justify-content-end">
                            <button class="btn btn-primary" type="submit">Edit product</button>
                        </div>
                    </div>
                </form>
            
            </div>
        </div>
    </div>
        
</div>


</main>
{% endblock content %}

templates/admin_app/pages/project_add.html
{% extends "admin_app/components/base.html" %}
{% load static %}
{% block content %}

{% include 'admin_app/components/header.html' %}
<div class="container-fluid py-4">
    {% include 'admin_app/components/alert.html' %}
    <div class="row">
        <div class="col-md-12">
        <div class="card">
            <div class="card-header pb-0">
            <div class="d-flex align-items-center">
                <p class="mb-0">Add Project</p>
                <!-- <button class="btn btn-primary btn-sm ms-auto">Settings</button> -->
            </div>
            </div>
            <div class="card-body">
                <!-- <p class="text-uppercase text-sm">User Information</p> -->
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_image" class="form-control-label">Image:690 x 500px</label>
                            
                            <input type="file" name="image" class="form-control" required>
                        </div>
                        </div>
                        <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_head" class="form-control-label">Head:</label>
                            <input type="text" name="head" maxlength="500" class="form-control" >
                        </div>
                        </div>
                        <div class="col-md-12">
                        <div class="form-group">
                            <label for="id_description" class="form-control-label">Description:</label>
                            <textarea name="description" maxlength="1000" class="form-control" ></textarea>
                        </div>
                        </div>
                        <!-- <div class="col-md-12">
                            <div class="form-group">
                                <label for="id_status" class="form-control-label">Status:</label>
                                <input type="checkbox" name="status">
                            </div>
                        </div> -->
                        <div class="col-md-12 d-flex justify-content-end">
                            <button class="btn btn-primary" type="submit">Add Project</button>
                        </div>
                    </div>
                </form>
            
            </div>
        </div>
    </div>
        
</div>


</main>
{% endblock content %}

templates/admin_app/pages/project_edit.html
{% extends "admin_app/components/base.html" %}
{% load static %}
{% block content %}

{% include 'admin_app/components/header.html' %}
<div class="container-fluid py-4">
    {% include 'admin_app/components/alert.html' %}
    <div class="row">
        <div class="col-md-12">
        <div class="card">
            <div class="card-header pb-0">
            <div class="d-flex align-items-center">
                <p class="mb-0">Edit Project</p>
                <!-- <button class="btn btn-primary btn-sm ms-auto">Settings</button> -->
            </div>
            </div>
            <div class="card-body">
                <!-- <p class="text-uppercase text-sm">User Information</p> -->
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_image" class="form-control-label">Image:690 x 500px</label>
                            <input type="file" name="image"  class="form-control" >
                        </div>
                        </div>
                        <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_head" class="form-control-label">Head:</label>
                            <input type="text" name="head" value="{{ project.head }}" maxlength="500" class="form-control" >
    
                        </div>
                        </div>
                        <div class="col-md-12">
                        <div class="form-group">
                            <label for="id_description" class="form-control-label">Description:</label>
                            <textarea name="description" maxlength="1000" class="form-control" >{{ project.description }}</textarea>
                        </div>
                        </div>
                        <!-- <div class="col-md-12">
                            <div class="form-group">
                                <label for="id_status" class="form-control-label">Status:</label>
                                <input type="checkbox" name="status" {% if project.status %}checked{% endif %}>
                            </div>
                        </div> -->
                        <div class="col-md-12 d-flex justify-content-end">
                            <button class="btn btn-primary" type="submit">Edit Project</button>
                        </div>
                    </div>
                </form>
            
            </div>
        </div>
    </div>
        
</div>


</main>
{% endblock content %}